receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9317
      http:
        endpoint: 0.0.0.0:9318

processors:
  batch: {}

exporters:
  otlp_grpc/jaeger:
    endpoint: jaeger-tracing:4317
    tls:
      insecure: true
  otlp_http/victoriametrics:
    metrics_endpoint: http://victoria-metrics:8428/opentelemetry/v1/metrics
  otlp_http/seq:
    endpoint: http://seq-log:80/ingest/otlp

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679

service:
  telemetry:
    traces:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://jaeger-tracing:4318
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/victoriametrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/seq]
