receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:9317
      http:
        endpoint: otel-collector:9318

processors:
  batch:
  delta_to_cumulative:
    max_stale: 1m
  cumulativetodelta:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
  zpages:
    endpoint: otel-collector:55679

exporters:
  debug:
    verbosity: detailed
  otlp_grpc/jaeger:
    endpoint: jaeger-tracing:4317
    tls:
      insecure: true
  otlp_http/seq:
    endpoint: "http://seq-log:5341/ingest/otlp"
  otlp_http/victoriametrics:
    compression: gzip
    encoding: proto
    endpoint: "http://victoria-metrics:8428/opentelemetry"
    tls:
      insecure: true
service:
  extensions: [zpages, pprof, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/jaeger]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/seq]
    metrics:
      receivers: [otlp]
      processors: [delta_to_cumulative]
      exporters: [otlp_http/victoriametrics, debug]
